repos:
-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    - id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
-   repo: local
    hooks:
        - id: rustfmt
          name: rustfmt
          language: system
          entry: bash -c "$(git rev-parse --show-toplevel)/pre-commit/pre-commit_rustfmt.sh"
          files: \.rs$
          types:
              - file
              - rust

