[package]
name = "day_01"
version = "0.1.0"
authors = ["Daniel Antrim <dantrim@lbl.gov>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
itertools = "0.9.0"
