[package]
name = "day_15"
version = "0.1.0"
authors = ["Daniel Antrim <dantrim@lbl.gov>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
